name: toledotour

environment:
  sdk: ">=2.18.2 <3.0.0"  # Ajusta para coincidir con Flutter 3.3.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.6.1
  location: ^5.0.3
  flutter_plugin_android_lifecycle: ^2.0.19  # Requerido para V2 embedding

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1  # Versión compatible con Dart 2.18