name: Flutter CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-android:
    name: Build & Test Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter (3.29.3)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'  # Versión actualizada 
          channel: 'stable'

      - name: Install dependencies
        run: |
          flutter pub get
          flutter pub upgrade --major-versions

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build APK (release)
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    name: Build & Test iOS
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter (3.29.3)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'  # Versión actualizada
          channel: 'stable'

      - name: Install dependencies
        run: |
          flutter pub get
          flutter pub upgrade --major-versions

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Upload iOS build
        uses: actions/upload-artifact@v4
        with:
          name: ios-release
          path: build/ios/iphoneos/Runner.app